name: vexed-me-prod

services:
  nginx:
    image: nginx
    volumes:
     - ../../nginx/templates:/etc/nginx/templates:ro
     - ../../certbot/www/:/var/www/certbot:ro
     - ../../certbot/letsencrypt/:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=vexed.me
  certbot:
    image: certbot/certbot
    volumes:
      - ../../certbot/www/:/var/www/certbot:rw
      - ../../certbot/letsencrypt/:/etc/letsencrypt:rw
  crawler:
    build:
      target: prod
    volumes:
      - crawler_node_modules:/app/node_modules
    restart: unless-stopped
  web:
    build:
      target: prod
    volumes:
      - web_node_modules:/app/node_modules
      - web_next:/app/.next
    restart: unless-stopped

volumes:
  crawler_node_modules:
  web_node_modules:
  web_next:
