name: vexed-me-prod

services:
  nginx:
    image: nginx
    volumes:
     - ../../nginx/templates:/etc/nginx/templates:ro
     - ../../certbot/www/:/var/www/certbot:ro
     - ../../certbot/letsencrypt/:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=vexed.me
    networks:
      frontend:
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    volumes:
      - ../../certbot/www/:/var/www/certbot:rw
      - ../../certbot/letsencrypt/:/etc/letsencrypt:rw
    profiles:
      - donotstart
  redis:
    networks:
      backend:
        ipv4_address: 172.16.1.168
    restart: unless-stopped
  crawler:
    build:
      target: prod
    volumes:
      - crawler_node_modules:/app/node_modules
    networks:
      backend:
    restart: unless-stopped
  web:
    build:
      target: prod
    volumes:
      - web_node_modules:/app/node_modules
      - web_next:/app/.next
    networks:
      frontend:
        ipv4_address: 172.16.0.168
      backend:
    restart: unless-stopped

volumes:
  crawler_node_modules:
  web_node_modules:
  web_next:

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.254
  backend:
    ipam:
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.254
